config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get 'search/index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :init_octokit

  def index
    if params[:search]
      date_count = {today: 0, within7days: 0, earlier: 0}
      issue_times = @client.list_issues(params[:search]).select{ |x| !x[:pull_request] }
                    .map{ |x| x[:created_at] }
      issue_times.map{|x|
        if x > 24.hours.ago
          date_count[:today] += 1
        elsif x > 7.days.ago
          date_count[:within7days] += 1
        else
          date_count[:earlier] += 1
        end
      }
      @values = date_count.values
    end
  end

  private

  def init_octokit
    Octokit.auto_paginate = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShippableAssignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <h2><%= link_to 'GitHub issue counter', '/' %></h2>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/search/index.html.erb
<p>&nbsp;

<div class="container">
  <h3>Enter GitHub repository</h3>
  <%= form_tag(search_index_path,method: "get") do %>
    <%= text_field_tag :search, params[:search], size: 50, placeholder: 'Enter repo in the form <owner-name>/<repo-name>' %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

</br>

<div class="container">
  <% if @values %>
    <table class="table table-bordered table-striped">
      <thead>
        <th>Commit time range</th>
        <th>Commit count</th>
      </thead>
      <tbody>
        <tr>
          <td>Within the last 24 hours</td>
          <td><%=@values[0] %></td>
        </tr>
        <tr>
          <td>Within the last day and last week</td>
          <td><%= @values[1] %></td>
        </tr>
        <tr>
          <td>Older than a week</td>
          <td><%= @values[2] %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>